#! /usr/bin/env perl
#
# Description: A simple script to allow new author addition (no changes possible)
#
#        Name: AuthorAddForm
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: Eric Vaandering (ewv@fnal.gov)
#

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA


use CGI qw(-nosticky);
use DBI;

require "DocDBGlobals.pm";
require "FormElements.pm";
require "Scripts.pm";
require "AuthorSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

GetInstitutions();
GetAuthors();

print $query -> header( -charset => $HTTP_ENCODING );
DocDBHeader("Add Authors","",-scripts => ["PopUps"]);

print "<div id=\"AuthorAddFormContainer\" class=\"w3-container\">\n";
print $query -> start_multipart_form('POST',"$AuthorAdd");

print "<div class=\"w3-panel w3-paper w3-border w3-border-gray w3-round w3-padding\">\n";
print "<p><b>You are about to add an author to the $Project document
database.</b> Anyone is allowed to add authors. <b>Please be
careful</b> and make sure to put the author's first name, last name, and
middle initials (with periods) in the right place. If you make a mistake,
<span class=\"w3-text-red\"><b>DO NOT</b></span> enter the author again. Contact an
<a href=\"mailto:$DBWebMasterEmail\" class=\"w3-text-docdb-color\">administrator</a> and explain the problem.
<b>Required fields are denoted by $RequiredMark.</b> Click any
<a href=\"#\" class=\"w3-text-docdb-color\">highlighted link</a> for quick help.</p>\n";

print "<table class=\"w3-table w3-bordered no-row-lines\">\n";
print "<tr>\n";
print "<td class=\"w3-padding\">\n"; InstitutionSelect(-required => $TRUE); print "</td>\n";
print "<td class=\"w3-padding\">\n"; NameEntryBox();      print "</td>\n";
print "</tr>\n";
print "<tr><td class=\"w3-padding\" colspan=\"2\">";
print $query -> submit (-class => "w3-button w3-docdb-color w3-border w3-border-black w3-round", -value => "Add Author");
print "</td></tr></table>\n";
print "</div><!-- Closing div w3-panel -->\n";
print $query -> end_multipart_form;

print "<h3 style=\"margin-bottom:0px!important\">Existing Authors:</h3>\n";

AuthorsTable();

print "</div><!-- Closing div id AuthorAddFormContainer -->\n";

DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
