#! /usr/bin/env perl
#
#        Name: DocumentDatabase
# Description: The Document Database homepage. Give the user various ways to
#              view documents, a link to ways to change documents, and a list
#              of the most recently updated documents.
#
#      Author: Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2018 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

# TODO: Do a redirect for first time users of shibboleth?

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "SecuritySQL.pm";
require "SecurityHTML.pm";
require "Security.pm";
require "Scripts.pm";
require "FormElements.pm";
require "XRefSQL.pm";

require "Messages.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
GetSecurityGroups();

my $CertificateStatus;
if ($UserValidation eq "certificate") {
  require "CertificateUtilities.pm";
  $CertificateStatus = CertificateStatus();
}

my @Scripts = ("PopUps");
push @Scripts,"jquery/jquery-3.5.1.slim.min","jquery/jquery.tablesorter.min","jquery/jquery.tablesorter.widgets";
@JQueryElements = ("tablesorter");
push @Scripts,"JQueryReady";

print $query->header( -charset => $HTTP_ENCODING );
if ($UserValidation eq "certificate" && $CertificateStatus ne "verified") {
  DocDBHeader("$Project Document Database","Document Database Home", -scripts => ["PopUps"], -refresh => "5;url=$CertificateApplyForm");
} else {
  DocDBHeader("$Project Document Database","Document Database Home", -scripts => \@Scripts, -jqueryelements => \@JQueryElements);
}

my $PersonalAccountLink = PersonalAccountLink();

# Get today's sessions
require "SQLUtilities.pm";  # Required for SQLNow()
# TEMPORARY: Using hardcoded date for testing - REMOVE BEFORE COMMITTING
# my $TodayDate = "2025-06-04";  # Using June 4, 2025 for testing (ShowCalendar?year=2025&month=6&day=4)
my $TodayDate = SQLNow(-dateonly => $TRUE);  # Get actual current date
my @TodaySessionIDs = ();
if ($Preferences{Components}{Calendar}) {
  require "MeetingSQL.pm";
  require "MeetingSecurityUtilities.pm";
  require "Sorts.pm";
  require "ResponseElements.pm";
  @TodaySessionIDs = FetchSessionsByDate($TodayDate);
  # Filter out undefined sessions and only keep accessible sessions (FetchSessionsByDate already calls FetchSessionByID)
  @TodaySessionIDs = grep { 
    my $SessionID = $_;
    $SessionID && exists $Sessions{$SessionID}{ConferenceID} && CanAccessMeeting($Sessions{$SessionID}{ConferenceID});
  } @TodaySessionIDs;
  # Sort sessions by time
  @TodaySessionIDs = sort SessionsByDateTime @TodaySessionIDs;
}

print "<div id=\"DocDBHomeBody\" class=\"w3-container w3-row\">\n";

### Header Messages (full width)

DocDBHomeHeader();

### Left Column

print "<div id=\"LeftColumn3ColWrapper\" class=\"w3-quarter\">\n";
print "<div id=\"LeftColumnUser\" class=\"w3-card w3-paper w3-border w3-border-gray w3-round w3-margin-top\">\n";
print "<div class=\"w3-center\" style=\"font-weight:700;margin-top:4px;\"><span style=\"text-decoration:underline;\">User Information</span></div>\n";
print "<div id=\"LeftBarBlock\" class=\"w3-bar-block\">\n";
if (!$Public or $UserValidation eq "FNALSSO") {  # Public set if not in any groups. Should be able to apply if not in groups
  if ($PersonalAccountLink) {
    print "<div id=\"LeftBarPersonalAccountLink\" class=\"w3-bar-item w3-button\">$PersonalAccountLink</div><!-- Closing div id LeftBarPersonalAccountLink -->\n";
  }
  print "<div id=\"LeftBarPreferencesLink\" class=\"w3-bar-item w3-button\"><a href=\"$SelectPrefs\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">Preferences</a></div><!-- Closing div id LeftBarPreferencesLink -->\n";
  if ($UserValidation eq "FNALSSO") {
    print "<div id=\"LeftBarApplyToGroupsLink\" class=\"w3-bar-item w3-button\"><a href=\"$CertificateApplyForm\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">Apply to Groups</a></div><!-- Closing div id LeftBarApplyToGroupsLink -->\n";
  }
  if ($UserValidation eq "certificate" || $UserValidation eq "shibboleth" || $UserValidation eq "FNALSSO") {
    print "<div id=\"LeftBarGroupLimitLink\" class=\"w3-bar-item w3-button\"><strong>",&GroupLimitLink(),"</strong></div><!-- Closing div id LeftBarGroupLimitLink -->\n";
  }
}

foreach my $Text (@{ $ProjectMessages{Homepage}{LeftColumn} }) {
  print "<div id=\"LeftBarProjectMessage\" class=\"w3-bar-item w3-button\"><strong>$Text</strong></div><!-- Closing div id LeftBarProjectMessage -->\n";
}
print "</div><!-- Closing div id LeftBarBlock -->\n";

print "</div><!-- Closing div id LeftColumnUser -->\n";

### Today's Schedule module
if ($Preferences{Components}{Calendar} && @TodaySessionIDs) {
  require "MeetingHTML.pm";
  require "EventUtilities.pm";
  require "SQLUtilities.pm";
  require "ResponseElements.pm";
  print "<div id=\"TodaysSchedule\" class=\"w3-card w3-paper w3-pale-green w3-border w3-border-gray w3-round w3-margin-top\">\n";
  print "<div class=\"w3-center\" style=\"font-weight:700;margin-top:4px;\"><i class=\"fa-regular fa-face-smile-beam\"></i>&nbsp;<span style=\"text-decoration:underline;\">Today's Event Schedule</span>&nbsp;<i class=\"fa-regular fa-face-smile-beam\"></i></div>\n";
  print "<div class=\"w3-bar-block\">\n";
  foreach my $SessionID (@TodaySessionIDs) {
    next unless $SessionID && exists $Sessions{$SessionID}{StartTime};
    my $StartTime = EuroTimeHM($Sessions{$SessionID}{StartTime});
    my $EndTime = TruncateSeconds(SessionEndTime($SessionID));
    my $TimeDisplay = $StartTime;
    if ($EndTime && $EndTime ne $StartTime) {
      $TimeDisplay .= " &ndash; " . $EndTime;
    }
    my $SessionLink = SessionLink(-sessionid => $SessionID, -format => "full");
    if ($SessionLink) {
      print "<div class=\"w3-bar-item w3-button w3-hover-white\">\n";
      print "<i class=\"fa-solid fa-clock\"></i>&nbsp;<strong>$TimeDisplay</strong><br/>\n";
      print "$SessionLink\n";
      print "</div>\n";
    }
  }
  print "</div><!-- Closing div w3-bar-block -->\n";
  print "</div><!-- Closing div id TodaysSchedule -->\n";
}

print "<div id=\"HomepageNavigationChoices\" class=\"w3-card w3-paper w3-border w3-border-gray w3-round w3-margin-top\">\n";
print "<div class=\"w3-center\" style=\"font-weight:700;margin-top:4px;\"><span style=\"text-decoration:underline;\">Navigation</span></div>\n";
print "<div class=\"w3-bar-block\">\n";
if (CanCreate()) {
  print "<div class=\"w3-bar-item w3-button\"><a href=\"$ModifyHome\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">Modify Homepage</a></div>\n";
}
if ($Preferences{Components}{Calendar}) {
  print "<div class=\"w3-bar-item w3-button\"><a href=\"$ShowCalendar\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">Show Calendar</a></div>\n";
}
print "<div class=\"w3-bar-item w3-button\"><a href=\"$ListAuthors\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">Author List</a></div>\n";
print "<div class=\"w3-bar-item w3-button\"><a href=\"$ListBy?days=30\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">Recent Documents</a></div>\n";
print "</div><!-- Closing div w3-bar-block -->\n";
print "</div><!-- Closing div id HomepageNavigationChoices -->\n";

print "<div id=\"SearchAndShow\" class=\"w3-card w3-paper w3-border w3-border-gray w3-round w3-margin-top\">\n";

print "<div class=\"w3-center\" style=\"font-weight:700;margin-top:4px;\"><span style=\"text-decoration:underline;\">Search and Show</span></div>\n";
print "<div class=\"w3-bar-block\">\n";

# SEARCH
print "<div id=\"HomepageSearchChoice\" class=\"w3-bar-item w3-padding\">\n";
my $SearchDiv  = $query -> start_form('POST',$Search);
   $SearchDiv .= "<div id=\"SearchFormContainer\" class=\"w3-row\">\n";
   $SearchDiv .= "<div class=\"w3-col s12 m10 l10\" style=\"padding-right:10px;\">\n";
   $SearchDiv .= $query -> textfield(-name => "simpletext", -maxlength => 300, -class => "w3-input w3-border w3-round w3-padding-small", -style => "min-width:120px;", -placeholder => "Enter search terms...");
   $SearchDiv .= "</div>\n";
   $SearchDiv .= "<div class=\"w3-col s12 m2 l2 w3-center\">\n";
   $SearchDiv .= "<button type=\"submit\" class=\"w3-button w3-docdb-color w3-border w3-border-black w3-round\" style=\"padding:8px;\"><i class=\"fa-solid fa-magnifying-glass w3-text-white\"></i></button>\n";
   $SearchDiv .= "</div>\n";
   $SearchDiv .= $query -> hidden(-name => "simple", -default => '1');
   $SearchDiv .= "</div><!-- Closing div id SearchFormContainer -->\n";
   $SearchDiv .= $query -> end_form;
print "$SearchDiv";
print "</div><!-- Closing div id HomepageSearchChoice -->\n";

# SHOW
print "<div id=\"HomepageShowChoice\" class=\"w3-bar-item w3-padding\">\n";
my $ShowForm  = $query -> start_form('POST',$ShowDocument);
   $ShowForm .= "<div id=\"ShowFormContainer\" class=\"w3-row\">\n";
   $ShowForm .= "<div class=\"w3-col s12 m5 l5\" style=\"padding-right:10px;\">\n";
   $ShowForm .= $query -> textfield(-name => "docid", -maxlength => 6, -class => "w3-input w3-border w3-round w3-padding-small", -style => "min-width:60px;", -placeholder => "Doc-ID");
   $ShowForm .= "</div>\n";
   $ShowForm .= "<div class=\"w3-col s12 m5 l5\" style=\"padding-right:10px;\">\n";
   $ShowForm .= $query -> textfield(-name => "version", -maxlength => 3, -class => "w3-input w3-border w3-round w3-padding-small", -style => "min-width:50px;", -placeholder => "Version");
   $ShowForm .= "</div>\n";
   $ShowForm .= "<div class=\"w3-col s12 m2 l2 w3-center\">\n";
   $ShowForm .= "<button type=\"submit\" class=\"w3-button w3-docdb-color w3-border w3-border-black w3-round\" style=\"padding:8px;\"><i class=\"fa-solid fa-eye w3-text-white\"></i></button>\n";
   $ShowForm .= "</div>\n";
   $ShowForm .= "</div><!-- Closing div id ShowFormContainer -->\n";
   $ShowForm .= $query -> end_form;
print "$ShowForm";
print "</div><!-- Closing div id HomepageShowChoice -->\n";

print "<div id=\"HomepageAdvancedLink\" class=\"w3-bar-item w3-button w3-center\">\n";
print "<a href=\"$SearchForm#Advanced\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">Advanced Search</a>\n";
print "</div><!-- Closing div id HomepageAdvancedLink -->\n";

print "</div><!-- Closing div w3-bar-block -->\n";
print "</div><!-- Closing div id SearchAndShow -->\n";

print "</div><!-- Closing div id LeftColumn3ColWrapper -->\n";

### Main Column

print "<div id=\"MainColumn3Col\" class=\"w3-threequarter\">\n";

if (CanAdminister()) {
  print "<div id=\"HomepageAdminChoice\" class=\"w3-padding\"><strong><a href=\"$AdministerHome\" class=\"w3-text-docdb-color\">Administer DocDB</a></strong></div><!-- Closing div id HomepageAdminChoice -->\n";
}

# Last modified pulldown

# COMMENTED OUT: Documents modified in the last N days form
# if ($Preferences{Components}{LastModifiedHome}) {
#   print "<div id=\"HomepageLastModifiedChoice\" class=\"w3-margin-top\">\n";
#   print $query -> start_form('POST',$ListBy);
#   print "<div id=\"LastModifiedFormContainer\" class=\"w3-bar\">\n";
#   print $query -> submit (-value => "Show", -class => "w3-bar-item w3-button w3-docdb-color w3-border w3-border-black w3-round", -style => "width:100px;");
#   print "<span class=\"w3-bar-item\"><strong> documents modified in the last </strong></span>";
#   print "<span class=\"w3-bar-item\" style=\"padding:0!important;\">";
#   DaysPulldown($LastDays);
#   print "</span>";
#   print "<span class=\"w3-bar-item\"><strong> days</strong></span>";
#   print "</div><!-- Closing div id LastModifiedFormContainer -->\n";
#   print $query -> end_form;
#   print "</div><!-- Closing div id HomepageLastModifiedChoice -->\n";
# }

# Fill arrays that print lists of documents

# COMMENTED OUT: List section moved to header navigation dropdown
# my @FirstColumn  = ();
# my @OtherColumns = ();
# my @Spanners     = ();
# 
# push @FirstColumn,"<a href=\"$ListAuthors\" class=\"w3-text-docdb-color\">Authors</a>";
# push @FirstColumn,"<a href=\"$ListTopics\" class=\"w3-text-docdb-color\">Topics</a>";
# push @FirstColumn,"<a href=\"$ListGroups\" class=\"w3-text-docdb-color\">Groups</a>";
# push @FirstColumn,"<a href=\"$ListKeywords\" class=\"w3-text-docdb-color\">Keywords</a>";
# unless ($Public && !$PublicAccess{MeetingList}) {
#   push @FirstColumn,"<a href=\"$ListAllMeetings\" class=\"w3-text-docdb-color\">Events</a>";
# }
# if ($UserValidation eq "certificate" || $UserValidation eq "shibboleth" || $UserValidation eq "FNALSSO" ||
#     (!$Public && $Preferences{Options}{DynamicFullList}{Private}) ||
#     ( $Public && $Preferences{Options}{DynamicFullList}{Public})) {
#   push @FirstColumn,"<a href=\"$ListBy?alldocs=1\" class=\"w3-text-docdb-color\">All documents</a>";
# } else {
#   push @FirstColumn,"<a href=\"$web_root/Static/Lists/$remote_user/FullList.html\" class=\"w3-text-docdb-color\">All documents</a>";
# }

# COMMENTED OUT: List section moved to header navigation dropdown
# if ($UseSignoffs && (!$Public || $PublicAccess{MeetingList})) {
#   push @OtherColumns,"<a href=\"$ListManagedDocuments\" class=\"w3-text-docdb-color\">Managed documents</a>";
# }
# push @OtherColumns,@{ $ProjectMessages{Homepage}{DocumentLists} };
# push @Spanners,@MultiColumnDocumentLists;
# 
# # Print bulleted list for lists of documents
# 
# print "<div id=\"DocListMethodsHeader\" class=\"w3-panel w3-margin-left w3-paper w3-round w3-padding w3-border w3-border-gray\">\n";
# print "<strong>List:</strong>\n";
# 
# print "<ul id=\"DocListMethods\" class=\"w3-ul\">\n";
# 
# foreach my $Item (@FirstColumn) {
#   print "<li>&loz;&nbsp;",$Item,"</li>\n";
# }
# 
# foreach my $Item (@OtherColumns) {
#   print "<li>&loz;&nbsp;",$Item,"</li>\n";
# }
# 
# foreach my $Spanner (@Spanners) {
#   print "<li>&loz;&nbsp;",$Spanner,"</li>\n";
# }
# 
# print "</ul>\n";
# print "</div><!-- Closing div id DocListMethodsHeader -->\n";

# Fill arrays with stuff that goes in main, bold table

# Modified in last few days

{
  require "DocumentHTML.pm";
  require "DocumentUtilities.pm";

### Get list of documents

  my $SortBy  = "date";
  my $Reverse = 1;

  my $List = $dbh -> prepare("select DISTINCT(DocumentID) from DocumentRevision where Obsolete=0 and TO_DAYS(NOW())-TO_DAYS(TimeStamp)<=?");
     $List -> execute($HomeLastDays);

  my @DocumentIDs = ();
  my $DocumentID;
  $List -> bind_columns(undef, \($DocumentID));
  while ($List -> fetch) {
    push @DocumentIDs,$DocumentID;
  }

### Print table

  if (@DocumentIDs) { ### FIXME: Move both kinds of titles into DocumentTable
    my %FieldList = PrepareFieldList(-default => "Default");
    print "<div id=\"DocumentTableContainer\" class=\"w3-margin-top w3-margin-left\">\n";
    my $NumberOfDocuments = DocumentTable(-fieldlist => \%FieldList, -docids  => \@DocumentIDs,
                                          -sortby    => $SortBy,     -reverse => $Reverse,
                                          -maxdocs   => $HomeMaxDocs);
    print "</div><!-- Closing div id DocumentTableContainer -->\n";
    print "<div id=\"MainRecentDocs\" class=\"w3-margin-left\">\n";
    if ($#DocumentIDs >= $HomeMaxDocs) {
      print "<i>Last $HomeMaxDocs documents modified.</i>\n";
    } else {
      print "<i>Documents modified in the last $HomeLastDays days.</i>\n";
    }
    print "</div><!-- Closing div id MainRecentDocs -->\n";
  } else {
    print "<div id=\"MainRecentDocs\" class=\"w3-margin-left\">\n";
    print "<i>No documents have been modified in the past $HomeLastDays days, see more documents <a href=\"$ListBy?days=30\" class=\"w3-text-docdb-color\" style=\"text-decoration:none;\">here</a>.</i>\n";
    print "</div><!-- Closing div id MainRecentDocs -->\n";
  }
}

### Right column (wrapped around by middle column)

#print "<div id=\"RightColumn3Col\">\n";
#print "</div>\n";  # RightColumn3Col

print "</div><!-- Closing div id MainColumn3Col -->\n";

print "</div><!-- Closing div id DocDBHomeBody -->\n";

$EndTime  = new Benchmark;

DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
