#! /usr/bin/env perl
#
#        Name: DocumentDatabase
# Description: The Document Database homepage. Give the user various ways to
#              view documents, a link to ways to change documents, and a list
#              of the most recently updated documents.
#
#      Author: Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2018 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

# TODO: Do a redirect for first time users of shibboleth?

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "SecuritySQL.pm";
require "SecurityHTML.pm";
require "Security.pm";
require "Scripts.pm";
require "FormElements.pm";
require "XRefSQL.pm";

require "Messages.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
GetSecurityGroups();

my $CertificateStatus;
if ($UserValidation eq "certificate") {
  require "CertificateUtilities.pm";
  $CertificateStatus = CertificateStatus();
}

my @Scripts = ("PopUps");
push @Scripts,"jquery/jquery-3.5.1.slim.min","jquery/jquery.tablesorter.min","jquery/jquery.tablesorter.widgets";
@JQueryElements = ("tablesorter");
push @Scripts,"JQueryReady";

print $query->header( -charset => $HTTP_ENCODING );
if ($UserValidation eq "certificate" && $CertificateStatus ne "verified") {
  DocDBHeader("$Project Document Database","Document Database Home", -scripts => ["PopUps"], -refresh => "5;url=$CertificateApplyForm");
} else {
  DocDBHeader("$Project Document Database","Document Database Home", -scripts => \@Scripts, -jqueryelements => \@JQueryElements);
}

my $PersonalAccountLink = PersonalAccountLink();

print "<div id=\"DocDBHomeBody\" class=\"w3-container w3-row\">\n";

### Header Messages (full width)

DocDBHomeHeader();

### Left Column

print "<div id=\"LeftColumn3Col\" class=\"w3-quarter w3-light-gray w3-border w3-border-black\">\n";
print "<div id=\"LeftBarBlock\" class=\"w3-bar-block\">\n";
print "<div id=\"LeftBarInstructionsLink\" class=\"w3-bar-item\"><strong><a href=\"$DocDBInstructions\">Instructions</a></strong></div><!-- Closing div id LeftBarInstructionsLink -->\n";
if (!$Public or $UserValidation eq "FNALSSO") {  # Public set if not in any groups. Should be able to apply if not in groups
  if ($PersonalAccountLink) {
    print "<div id=\"LeftBarPersonalAccountLink\" class=\"w3-bar-item\"><strong>$PersonalAccountLink</strong></div><!-- Closing div id LeftBarPersonalAccountLink -->\n";
  }
  print "<div id=\"LeftBarPreferencesLink\" class=\"w3-bar-item\"><strong><a href=\"$SelectPrefs\">Preferences</a></strong></div><!-- Closing div id LeftBarPreferencesLink -->\n";
  if ($UserValidation eq "FNALSSO") {
    print "<div id=\"LeftBarApplyToGroupsLink\" class=\"w3-bar-item\"><strong><a href=\"$CertificateApplyForm\">Apply to Groups</a></strong></div><!-- Closing div id LeftBarApplyToGroupsLink -->\n";
  }
  if ($UserValidation eq "certificate" || $UserValidation eq "shibboleth" || $UserValidation eq "FNALSSO") {
    print "<div id=\"LeftBarGroupLimitLink\" class=\"w3-bar-item\"><strong>",&GroupLimitLink(),"</strong></div><!-- Closing div id LeftBarGroupLimitLink -->\n";
  }
}
print "<div id=\"LeftBarStatisticsLink\" class=\"w3-bar-item\"><strong><a href=\"$Statistics\">DocDB Statistics</a></strong></div><!-- Closing div id LeftBarStatisticsLink -->\n";

foreach my $Text (@{ $ProjectMessages{Homepage}{LeftColumn} }) {
  print "<div id=\"LeftBarProjectMessage\" class=\"w3-bar-item\"><strong>$Text</strong></div><!-- Closing div id LeftBarProjectMessage -->\n";
}
print "<div id=\"LeftBarAboutDocDBLink\" class=\"w3-bar-item\"><strong><a href=\"$DocDBHome\">About DocDB</a></strong></div><!-- Closing div id LeftBarAboutDocDBLink -->\n";
print "</div><!-- Closing div id LeftBarBlock -->\n";

print "</div><!-- Closing div id LeftColumn3Col -->\n";

### Main Column

print "<div id=\"MainColumn3Col\" class=\"w3-threequarter\">\n";

if (CanAdminister()) {
  print "<div id=\"HomepageAdminChoice\" class=\"w3-padding\"><strong><a href=\"$AdministerHome\">Administer DocDB</a></strong></div><!-- Closing div id HomepageAdminChoice -->\n";
}
if (CanCreate()) {
  print "<div id=\"HomepageCreateChoice\" class=\"w3-padding\"><strong><a href=\"$ModifyHome\">Create or change documents or other information</a></strong></div><!-- Closing div id HomepageCreateChoice -->\n";
}

my @ExternalDocDBIDs = GetAllExternalDocDBs();
my $SearchDiv  = $query -> start_form('POST',$Search);
   $SearchDiv .= "<div id=\"SearchFormContainer\" class=\"w3-bar\">\n";
   $SearchDiv .= $query -> submit (-value => "Search", -class => "w3-bar-item w3-button w3-blue w3-border w3-border-black w3-round");
   $SearchDiv .= "<span class=\"w3-bar-item\"><strong>for</strong></span>";
   $SearchDiv .= "<span class=\"w3-bar-item\" style=\"padding:0!important;\">";
   $SearchDiv .= $query -> textfield(-name => "simpletext", -size => 40, -maxlength => 300, -class => "w3-input w3-border");
   $SearchDiv .= "</span>";
   $SearchDiv .= $query -> hidden(-name => "simple", -default => '1');
   $SearchDiv .= "<span class=\"w3-bar-item\"><strong>(<a href=\"$SearchForm#Advanced\">Advanced</a>";
if (@ExternalDocDBIDs) {
   $SearchDiv .= " or <a href=\"$XSearch\">Cross Search</a>";
}
   $SearchDiv .= ")</strong></span>";
   $SearchDiv .= "\n</div><!-- Closing div id SearchFormContainer -->\n";
   $SearchDiv .= $query -> end_form;

print "<div id=\"HomepageSearchChoice\" class=\"w3-padding\">$SearchDiv</div><!-- Closing div id HomepageSearchChoice -->\n";

my $ShowForm  = $query -> start_form('POST',$ShowDocument);
   $ShowForm .= "<div id=\"ShowFormContainer\" class=\"w3-bar\">\n";
   $ShowForm .= $query -> submit (-value => "Show", -class => "w3-bar-item w3-button w3-blue w3-border w3-border-black w3-round");
   $ShowForm .= "<span class=\"w3-bar-item\"><strong>$ShortProject-doc-#</strong></span>";
   $ShowForm .= "<span class=\"w3-bar-item\" style=\"padding:0!important;\">";
   $ShowForm .= $query -> textfield(-name => "docid", -size => 6, -maxlength => 6, -class => "w3-input w3-border");
   $ShowForm .= "</span>";
   $ShowForm .= "<span class=\"w3-bar-item\"><strong>-v</strong></span>";
   $ShowForm .= "<span class=\"w3-bar-item\" style=\"padding:0!important;\">";
   $ShowForm .= $query -> textfield(-name => "version", -size => 3, -maxlength => 3, -class => "w3-input w3-border");
   $ShowForm .= "</span>";
   $ShowForm .= "\n</div><!-- Closing div id ShowFormContainer -->\n";
   $ShowForm .= $query -> end_form;

print "<div id=\"HomepageShowChoice\" class=\"w3-padding\">$ShowForm</div><!-- Closing div id HomepageShowChoice -->\n";

# Last modified pulldown

if ($Preferences{Components}{LastModifiedHome}) {
  print "<div id=\"HomepageLastModifiedChoice\" class=\"w3-padding\">\n";
  print $query -> start_form('POST',$ListBy);
  print "<div id=\"LastModifiedFormContainer\" class=\"w3-bar\">\n";
  print $query -> submit (-value => "Show", -class => "w3-bar-item w3-button w3-blue w3-border w3-border-black w3-round");
  print "<span class=\"w3-bar-item\"><strong> documents modified in the last </strong></span>";
  print "<span class=\"w3-bar-item\" style=\"padding:0!important;\">";
  DaysPulldown($LastDays);
  print "</span>";
  print "<span class=\"w3-bar-item\"><strong> days</strong></span>";
  print "</div><!-- Closing div id LastModifiedFormContainer -->\n";
  print $query -> end_form;
  print "</div><!-- Closing div id HomepageLastModifiedChoice -->\n";
}

if ($Preferences{Components}{Calendar}) {
  print "<div id=\"HomepageCalendarChoice\" class=\"w3-padding\">\n";
  print "<strong><a href=\"$ShowCalendar\">Calendar</a> of events or <a href=\"$ShowCalendar?todayonly=1\">today's</a> events</strong>";
  print "</div><!-- Closing div id HomepageCalendarChoice -->\n";
}

# Fill arrays that print lists of documents

my @FirstColumn  = ();
my @OtherColumns = ();
my @Spanners     = ();

push @FirstColumn,"<a href=\"$ListAuthors\">Authors</a>";
push @FirstColumn,"<a href=\"$ListTopics\">Topics</a>";
push @FirstColumn,"<a href=\"$ListGroups\">Groups</a>";
push @FirstColumn,"<a href=\"$ListKeywords\">Keywords</a>";
unless ($Public && !$PublicAccess{MeetingList}) {
  push @FirstColumn,"<a href=\"$ListAllMeetings\">Events</a>";
}
if ($UserValidation eq "certificate" || $UserValidation eq "shibboleth" || $UserValidation eq "FNALSSO" ||
    (!$Public && $Preferences{Options}{DynamicFullList}{Private}) ||
    ( $Public && $Preferences{Options}{DynamicFullList}{Public})) {
  push @FirstColumn,"<a href=\"$ListBy?alldocs=1\">All documents</a>";
} else {
  push @FirstColumn,"<a href=\"$web_root/Static/Lists/$remote_user/FullList.html\">All documents</a>";
}

if ($UseSignoffs && (!$Public || $PublicAccess{MeetingList})) {
  push @OtherColumns,"<a href=\"$ListManagedDocuments\">Managed documents</a>";
}

push @OtherColumns,@{ $ProjectMessages{Homepage}{DocumentLists} };
push @Spanners,@MultiColumnDocumentLists;

# Print bulleted list for lists of documents

print "<div id=\"DocListMethodsHeader\" class=\"w3-padding\">\n";
print "<strong>List:</strong>\n";
print "</div><!-- Closing div id DocListMethodsHeader -->\n";

print "<ul id=\"DocListMethods\" class=\"w3-ul w3-padding\">\n";

foreach my $Item (@FirstColumn) {
  print "<li>&loz;&nbsp;",$Item,"</li>\n";
}

foreach my $Item (@OtherColumns) {
  print "<li>&loz;&nbsp;",$Item,"</li>\n";
}

foreach my $Spanner (@Spanners) {
  print "<li>&loz;&nbsp;",$Spanner,"</li>\n";
}

print "</ul>\n";

# Fill arrays with stuff that goes in main, bold table

# Modified in last few days

{
  require "DocumentHTML.pm";
  require "DocumentUtilities.pm";

### Get list of documents

  my $SortBy  = "date";
  my $Reverse = 1;

  my $List = $dbh -> prepare("select DISTINCT(DocumentID) from DocumentRevision where Obsolete=0 and TO_DAYS(NOW())-TO_DAYS(TimeStamp)<=?");
     $List -> execute($HomeLastDays);

  my @DocumentIDs = ();
  my $DocumentID;
  $List -> bind_columns(undef, \($DocumentID));
  while ($List -> fetch) {
    push @DocumentIDs,$DocumentID;
  }

### Print table

  if (@DocumentIDs) { ### FIXME: Move both kinds of titles into DocumentTable
    print "<div id=\"DocumentListHeader\" class=\"w3-padding\">\n";
    print "<div id=\"hr\" class=\"w3-panel w3-black\"></div>\n";
    print "<h4>\n";
    if ($#DocumentIDs >= $HomeMaxDocs) {
      print "Last $HomeMaxDocs documents modified\n";
    } else {
      print "Documents modified in the last $HomeLastDays days\n";
    }
    print "</h4>\n";
    print "</div><!-- Closing div id DocumentListHeader -->\n";
  }

  my %FieldList = PrepareFieldList(-default => "Default");
  print "<div id=\"DocumentTableContainer\" class=\"w3-container\">\n";
  my $NumberOfDocuments = DocumentTable(-fieldlist => \%FieldList, -docids  => \@DocumentIDs,
                                        -sortby    => $SortBy,     -reverse => $Reverse,
                                        -maxdocs   => $HomeMaxDocs);
  print "</div><!-- Closing div id DocumentTableContainer -->\n";
}

### Right column (wrapped around by middle column)

#print "<div id=\"RightColumn3Col\">\n";
#print "</div>\n";  # RightColumn3Col

print "</div><!-- Closing div id MainColumn3Col -->\n";

print "</div><!-- Closing div id DocDBHomeBody -->\n";

$EndTime  = new Benchmark;

DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
