#! /usr/bin/env perl
#
#        Name: $RCSfile$
# Description: Print out various types of calendar (monthly/yearly/daily) and the events
#              on that day (or an indication that there are events)
#
#    Revision: $Revision$
#    Modified: $Author$ on $Date$
#
#      Author: Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

# N.B. There are reports of problems with this code when crossing Daylight Saving Time and
#      certain (non-US) timezones this is almost certainly because certain times don't exist
#      when clocks jump forward. Perhaps "midnight" doesn't exist for all days in all timezones?

use Benchmark; $StartTime = new Benchmark;
use CGI;
use CGI::Untaint;
use DBI;
use DateTime;

require "DocDBGlobals.pm";
require "DBUtilities.pm";
require "HTMLUtilities.pm";
require "UntaintInput.pm";
require "ResponseElements.pm";

require "MeetingSecurityUtilities.pm";

require "CalendarHTML.pm";
require "MeetingHTML.pm";

require "MeetingSQL.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
my $Untaint = CGI::Untaint -> new($query -> Vars);

my $Day = $Untaint -> extract(-as_integer => "day") || 0;
my $Month = $Untaint -> extract(-as_integer => "month") || 0;
my $Year = $Untaint -> extract(-as_integer => "year") || 0;
my $TodayOnly = $Untaint -> extract(-as_safehtml => "todayonly") || "";

CreateConnection();

### Start HTML

print $query -> header( -charset => $HTTP_ENCODING );

my $TitleDate;
my $FutureEventTable = $FALSE;
my $MonthEventTable  = $FALSE;
my $WindowStart;
my $WindowEnd;
my $WindowDays;
my $EventTableStart;
my $Today = DateTime -> now(time_zone => 'local');

push @DebugStack, "Today is ".$Today -> iso8601;

if ($TodayOnly) {
  $Month     = $Today -> month();
  $Year      = $Today -> year();
  $Day       = $Today -> day();
  my $Date = DateTime -> new(year => $Year, month => $Month, day => $Day);
  $TitleDate = $Day." ".$Date -> month_name()." ".$Year;
  #$FutureEventTable = $TRUE;
} elsif ($Day && $Month && $Year) {
  my $Date = DateTime -> new(year => $Year, month => $Month, day => $Day);
  $TitleDate = $Day." ".$Date -> month_name()." ".$Year;
} elsif ($Month && $Year) {
  my $Date = DateTime -> new(year => $Year, month => $Month, day => 1);
  $TitleDate = $Date -> month_name()." ".$Year;
  $EventTableStart = $Date -> clone();
  $MonthEventTable = $TRUE;
  $WindowStart = $Date -> ymd();;
  $WindowEnd  = DateTime -> last_day_of_month(year => $Year, month => $Month) -> ymd();
  $WindowDays = DateTime -> last_day_of_month(year => $Year, month => $Month) -> day();
} elsif ($Year) {
  $TitleDate = $Year;
  if ($Year == $Today -> year()) {
    $FutureEventTable = $TRUE;
  }
} else {
  $Month     = $Today -> month();
  $Year      = $Today -> year();
  $TitleDate = $Today -> month_name()." ".$Year;
  $FutureEventTable = $TRUE;
}

DocDBHeader("Calendar for $TitleDate");
EndPage(@ErrorStack);

print "<div id=\"CalendarBody\" class=\"w3-container w3-row\">\n";

if ($Day && $Month && $Year) {

  my $TheDay = DateTime -> new(year => $Year, month => $Month, day => $Day);

  my $PrevDay = $TheDay -> clone();
     $PrevDay -> add(days => -1);
  my $PrevDNum  = $PrevDay -> day();
  my $PrevMNum  = $PrevDay -> month();
  my $PrevName  = $PrevDay -> month_name();
  my $PrevYear  = $PrevDay -> year();

  my $NextDay = $TheDay -> clone();
     $NextDay -> add(days => 1);
  my $NextDNum  = $NextDay -> day();
  my $NextMNum  = $NextDay -> month();
  my $NextName  = $NextDay -> month_name();
  my $NextYear  = $NextDay -> year();

  print "<div class=\"w3-container\">\n";
  print "<div id=\"CalNavWrap\" class=\"w3-panel\">\n";
  print "<div id=\"CalendarNavigator\" class=\"w3-cell-row w3-center w3-margin-bottom w3-paper w3-round-large w3-border w3-border-light-gray w3-padding\">\n";
  print "<div class=\"w3-cell w3-cell-middle\">\n";
  print "<i class=\"fa-solid fa-chevron-left w3-text-teal\"></i>&nbsp;";
  print "<a href=\"".$ShowCalendar."?year=$PrevYear&amp;month=$PrevMNum&amp;day=$PrevDNum\" class=\"w3-large w3-text-teal\"><span class=\"\">$PrevDNum $PrevName $PrevYear</span></a>\n";
  print "</div><!-- Closing div w3-cell -->\n";
  print "<div class=\"w3-cell w3-cell-middle\" style=\"padding-left:2em; padding-right:2em;\">\n";
  print "<span class=\"w3-large\">$Day ";
  print "<a href=\"".$ShowCalendar."?year=$Year&amp;month=$Month\" class=\"w3-text-teal\">".$TheDay -> month_name()."</a> ";
  print "<a href=\"".$ShowCalendar."?year=$Year\" class=\"w3-text-teal\">$Year</a>";
  print "</span>\n";
  print "</div><!-- Closing div w3-cell -->\n";
  print "<div class=\"w3-cell w3-cell-middle\">\n";
  print "<a href=\"".$ShowCalendar."?year=$NextYear&amp;month=$NextMNum&amp;day=$NextDNum\" class=\"w3-large w3-text-teal\"><span class=\"\">$NextDNum $NextName $NextYear</span></a>&nbsp;";
  print "<i class=\"fa-solid fa-chevron-right w3-text-teal\"></i>\n";
  print "</div><!-- Closing div w3-cell -->\n";
  print "</div><!-- Closing div id CalendarNavigator -->\n";
  print "</div><!-- Closing div id CalNavWrap -->\n";
  print "</div><!-- Closing div w3-container -->\n";

  if (CanCreateMeeting()) {
    print "<div class=\"w3-container w3-margin-left w3-bar w3-center\">\n";
    print "<a href=\"".$SessionModify."?mode=new&amp;singlesession=1&amp;sessionyear=$Year&amp;sessionmonth=$Month&amp;sessionday=$Day\" class=\"w3-bar-item w3-button w3-teal w3-border w3-border-black w3-round\">Add a New Event on this Day</a>\n";
    print "</div><!-- Closing div w3-container w3-margin-left w3-bar w3-center -->\n";
  }

  PrintDayEvents(-year => $Year, -month => $Month, -day => $Day);
} elsif ($Month && $Year) {
  PrintCalendar(-year => $Year, -month => $Month);
} elsif ($Year) {
  print "<div class=\"w3-container w3-margin-bottom\">\n";
  print "<div id=\"CalNavWrap\" class=\"w3-panel\">\n";
  print "<div id=\"CalendarNavigator\" class=\"w3-cell-row w3-center w3-margin-bottom w3-paper w3-round-large w3-border w3-border-light-gray w3-padding\">\n";
  print "<div class=\"w3-cell w3-cell-middle\">\n";
  print "<i class=\"fa-solid fa-chevron-left w3-text-teal\"></i>&nbsp;";
  print "<a href=\"".$ShowCalendar."?year=".($Year - 1)."\" class=\"w3-large w3-text-teal\"><span class=\"\">".($Year - 1)."</span></a>\n";
  print "</div><!-- Closing div w3-cell -->\n";
  print "<div class=\"w3-cell w3-cell-middle\" style=\"padding-left:2em; padding-right:2em;\">\n";
  print "<span class=\"w3-large\">$Year</span>\n";
  print "</div><!-- Closing div w3-cell -->\n";
  print "<div class=\"w3-cell w3-cell-middle\">\n";
  print "<a href=\"".$ShowCalendar."?year=".($Year + 1)."\" class=\"w3-large w3-text-teal\"><span class=\"\">".($Year + 1)."</span></a>&nbsp;";
  print "<i class=\"fa-solid fa-chevron-right w3-text-teal\"></i>\n";
  print "</div><!-- Closing div w3-cell -->\n";
  print "</div><!-- Closing div id CalendarNavigator -->\n";
  print "</div><!-- Closing div id CalNavWrap -->\n";
  
  print "<div class=\"w3-grid\" style=\"display:grid; grid-template-columns:repeat(auto-fit, minmax(500px, 1fr)); gap:16px; align-items:start;\">\n";
  for $Month (1 .. 12) {
    my $MonthAbrv = $AbrvMonths[$Month - 1];
    my $MonthDivID = "$Year$MonthAbrv";
    print "<div class=\"w3-col w3-padding\">\n";
    print "<div id=\"$MonthDivID\" class=\"w3-card w3-white w3-border w3-border-gray w3-margin-bottom\">\n";
    PrintCalendar(-year => $Year, -month => $Month, -type => "year");
    print "</div><!-- Closing div id $MonthDivID -->\n";
    print "</div><!-- Closing div w3-col -->\n";
  }
  print "</div><!-- Closing div w3-grid -->\n";
  print "</div><!-- Closing div w3-container -->\n";
}

if ($FutureEventTable || $MonthEventTable) {
  if ($FutureEventTable) {
    my $TheDay   = $Today -> clone();
    $EventTableStart = $Today -> clone();
    $WindowStart = $TheDay -> ymd();
    $TheDay      -> add(days => 60);
    $WindowEnd   = $TheDay -> ymd();
    $WindowDays  = 60;
  }

  my @EventIDs = GetEventsByDate({-from => $WindowStart, -to => $WindowEnd});

  if (@EventIDs) {
    print "<div class=\"w3-container w3-margin-top w3-margin-bottom\">\n";
    print "<div class=\"w3-container w3-margin-top\">\n";
    print "<div id=\"EventsDetails\" class=\"w3-card w3-border w3-border-gray\">\n";
    print "<table class=\"w3-table w3-bordered w3-striped\">\n";
    print "<tr><th>Date</th><th>Time</th>";
    if ($FutureEventTable) {
      print "<th>Upcoming Events</th>";
    } else {
      print "<th>Events for Month</th>";
    }
    print "<th>Location</th><th>&nbsp;</th></tr>\n";
    my $TheDay = $EventTableStart -> clone();
    foreach my $i (1..$WindowDays) {
      my $Count = PrintDayEvents(-year => $TheDay -> year(), -month  => $TheDay -> month(),
                                 -day  => $TheDay -> day(),  -format => "multiday");
      $TheDay -> add(days => 1);
    }
    print "</table>\n";
    print "</div><!-- Closing div id EventsDetails -->\n";
    print "</div><!-- Closing div w3-container -->\n";
    print "</div><!-- Closing div w3-container -->\n";
  }
}

print "</div><!-- Closing div id CalendarBody -->\n";

$EndTime  = new Benchmark;

DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
